// EpiHack Arizona 2026 — pathogen knowledge-graph data for Cytoscape.
//
// Mirrors a subset of schema/deep/pathogens.sql plus the resource and
// focus-area nodes it links to. Each Cytoscape node ID matches its
// kg_node_id in the DuckLake graph for round-trip queryability.

window.EPIHACK_GRAPH = {

  nodes: [
    // -------- pathogens (16) --------
    { data: { id: 'pathogen.wnv',                    label: 'West Nile virus',                 kind: 'pathogen', pclass: 'virus',     icd10: 'A92.3',  notifiable: true }},
    { data: { id: 'pathogen.slev',                   label: 'St. Louis encephalitis virus',    kind: 'pathogen', pclass: 'virus',     icd10: 'A83.3',  notifiable: true }},
    { data: { id: 'pathogen.dengue',                 label: 'Dengue virus',                    kind: 'pathogen', pclass: 'virus',     icd10: 'A90',    notifiable: true }},
    { data: { id: 'pathogen.zika',                   label: 'Zika virus',                      kind: 'pathogen', pclass: 'virus',     icd10: 'A92.5',  notifiable: true }},
    { data: { id: 'pathogen.sin_nombre',             label: 'Sin Nombre virus (hantavirus)',   kind: 'pathogen', pclass: 'virus',     icd10: 'B33.4',  notifiable: true }},
    { data: { id: 'pathogen.y_pestis',               label: 'Yersinia pestis (plague)',        kind: 'pathogen', pclass: 'bacterium', icd10: 'A20',    notifiable: true }},
    { data: { id: 'pathogen.f_tularensis',           label: 'Francisella tularensis (tularemia)', kind: 'pathogen', pclass: 'bacterium', icd10: 'A21', notifiable: true }},
    { data: { id: 'pathogen.rickettsia_rickettsii',  label: 'Rickettsia rickettsii (RMSF)',    kind: 'pathogen', pclass: 'bacterium', icd10: 'A77.0',  notifiable: true }},
    { data: { id: 'pathogen.rabies',                 label: 'Rabies lyssavirus',               kind: 'pathogen', pclass: 'virus',     icd10: 'A82',    notifiable: true }},
    { data: { id: 'pathogen.h5n1',                   label: 'HPAI H5N1',                       kind: 'pathogen', pclass: 'virus',     icd10: 'J09.X2', notifiable: true }},
    { data: { id: 'pathogen.cwd_prion',              label: 'CWD prion',                       kind: 'pathogen', pclass: 'prion',     icd10: null,     notifiable: false }},
    { data: { id: 'pathogen.coccidioides',           label: 'Coccidioides spp. (Valley Fever)', kind: 'pathogen', pclass: 'fungus',    icd10: 'B38',    notifiable: true }},
    { data: { id: 'pathogen.borrelia',               label: 'Borrelia burgdorferi (Lyme)',     kind: 'pathogen', pclass: 'bacterium', icd10: 'A69.2',  notifiable: true }},
    { data: { id: 'pathogen.anaplasma',              label: 'Anaplasma phagocytophilum',       kind: 'pathogen', pclass: 'bacterium', icd10: 'A79.82', notifiable: true }},
    { data: { id: 'pathogen.babesia',                label: 'Babesia spp.',                    kind: 'pathogen', pclass: 'parasite',  icd10: 'B60.0',  notifiable: true }},
    { data: { id: 'pathogen.leptospira',             label: 'Leptospira spp.',                 kind: 'pathogen', pclass: 'bacterium', icd10: 'A27',    notifiable: true }},

    // -------- vectors (10) --------
    { data: { id: 'vector.culex_tarsalis',           label: 'Culex tarsalis',           kind: 'vector', vclass: 'mosquito' }},
    { data: { id: 'vector.culex_quinquefasciatus',   label: 'Culex quinquefasciatus',   kind: 'vector', vclass: 'mosquito' }},
    { data: { id: 'vector.aedes_aegypti',            label: 'Aedes aegypti',            kind: 'vector', vclass: 'mosquito' }},
    { data: { id: 'vector.aedes_albopictus',         label: 'Aedes albopictus',         kind: 'vector', vclass: 'mosquito' }},
    { data: { id: 'vector.rhipicephalus_sanguineus', label: 'Rhipicephalus sanguineus (brown dog tick)', kind: 'vector', vclass: 'tick' }},
    { data: { id: 'vector.ixodes_pacificus',         label: 'Ixodes pacificus (Western black-legged)',   kind: 'vector', vclass: 'tick' }},
    { data: { id: 'vector.dermacentor_andersoni',    label: 'Dermacentor andersoni',    kind: 'vector', vclass: 'tick' }},
    { data: { id: 'vector.dermacentor_variabilis',   label: 'Dermacentor variabilis',   kind: 'vector', vclass: 'tick' }},
    { data: { id: 'vector.oropsylla_montana',        label: 'Oropsylla montana (ground-squirrel flea)',  kind: 'vector', vclass: 'flea' }},
    { data: { id: 'vector.xenopsylla_cheopis',       label: 'Xenopsylla cheopis (oriental rat flea)',    kind: 'vector', vclass: 'flea' }},

    // -------- reservoirs (selection) --------
    { data: { id: 'reservoir.passerine_birds',       label: 'Passerine birds',        kind: 'reservoir' }},
    { data: { id: 'reservoir.deer_mouse',            label: 'Deer mouse (P. maniculatus)', kind: 'reservoir' }},
    { data: { id: 'reservoir.gunnison_prairie_dog', label: 'Gunnison\'s prairie dog', kind: 'reservoir' }},
    { data: { id: 'reservoir.rock_squirrel',         label: 'Rock squirrel',          kind: 'reservoir' }},
    { data: { id: 'reservoir.cottontail',            label: 'Cottontail rabbits',     kind: 'reservoir' }},
    { data: { id: 'reservoir.jackrabbit',            label: 'Jackrabbits',            kind: 'reservoir' }},
    { data: { id: 'reservoir.dogs',                  label: 'Domestic dogs',          kind: 'reservoir' }},
    { data: { id: 'reservoir.bats',                  label: 'Bats',                   kind: 'reservoir' }},
    { data: { id: 'reservoir.skunks',                label: 'Skunks',                 kind: 'reservoir' }},
    { data: { id: 'reservoir.foxes',                 label: 'Foxes',                  kind: 'reservoir' }},
    { data: { id: 'reservoir.waterfowl',             label: 'Wild waterfowl',         kind: 'reservoir' }},
    { data: { id: 'reservoir.dairy_cattle',          label: 'Dairy cattle',           kind: 'reservoir' }},
    { data: { id: 'reservoir.deer_elk',              label: 'Deer / elk',             kind: 'reservoir' }},
    { data: { id: 'reservoir.desert_soil',           label: 'Desert soil',            kind: 'reservoir' }},

    // -------- agencies / labs that surveil pathogens --------
    { data: { id: 'resource.adhs',                   label: 'ADHS', kind: 'resource', jur: 'state' }},
    { data: { id: 'resource.azgfd',                  label: 'AZGFD', kind: 'resource', jur: 'state' }},
    { data: { id: 'resource.mcdph_mcesd',            label: 'Maricopa Vector Control', kind: 'resource', jur: 'county' }},
    { data: { id: 'resource.pcdh',                   label: 'Pima Vector Control', kind: 'resource', jur: 'county' }},
    { data: { id: 'resource.coconino_hhs',           label: 'Coconino HHS', kind: 'resource', jur: 'county' }},
    { data: { id: 'resource.usgs_nwhc',              label: 'USGS NWHC / WHISPers', kind: 'resource', jur: 'federal' }},
    { data: { id: 'resource.usda_aphis_ws',          label: 'USDA APHIS Wildlife Services', kind: 'resource', jur: 'federal' }},
    { data: { id: 'resource.usfws_az',               label: 'USFWS (AZ)', kind: 'resource', jur: 'federal' }},
    { data: { id: 'resource.neon',                   label: 'NEON', kind: 'resource', jur: 'federal_funded_research' }},
    { data: { id: 'resource.ua_extension_tickcheck', label: 'Great Arizona Tick Check', kind: 'resource', jur: 'academic' }},
    { data: { id: 'resource.azvdl',                  label: 'AZVDL', kind: 'resource', jur: 'academic' }},
    { data: { id: 'resource.nau_pmi',                label: 'NAU PMI', kind: 'resource', jur: 'academic' }},
    { data: { id: 'resource.navajo_ec',              label: 'Navajo Epidemiology Center', kind: 'resource', jur: 'tribal' }},

    // -------- focus areas (top-level diseases / disease classes) --------
    { data: { id: 'focus.wnv',          label: 'WNV',          kind: 'focus' }},
    { data: { id: 'focus.plague',       label: 'Plague',       kind: 'focus' }},
    { data: { id: 'focus.hantavirus',   label: 'Hantavirus',   kind: 'focus' }},
    { data: { id: 'focus.rmsf',         label: 'RMSF',         kind: 'focus' }},
    { data: { id: 'focus.tularemia',    label: 'Tularemia',    kind: 'focus' }},
    { data: { id: 'focus.rabies',       label: 'Rabies',       kind: 'focus' }},
    { data: { id: 'focus.hpai',         label: 'HPAI',         kind: 'focus' }},
    { data: { id: 'focus.cwd',          label: 'CWD',          kind: 'focus' }},
    { data: { id: 'focus.zoonotic',     label: 'Zoonotic (general)', kind: 'focus' }},
    { data: { id: 'focus.vector_borne', label: 'Vector-borne (general)', kind: 'focus' }}
  ],

  edges: [
    // ---- transmittedBy: pathogen -> vector ----
    { data: { source: 'pathogen.wnv',                   target: 'vector.culex_tarsalis',          predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.wnv',                   target: 'vector.culex_quinquefasciatus',  predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.slev',                  target: 'vector.culex_tarsalis',          predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.dengue',                target: 'vector.aedes_aegypti',           predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.dengue',                target: 'vector.aedes_albopictus',        predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.zika',                  target: 'vector.aedes_aegypti',           predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.rickettsia_rickettsii', target: 'vector.rhipicephalus_sanguineus', predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.rickettsia_rickettsii', target: 'vector.dermacentor_andersoni',   predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.rickettsia_rickettsii', target: 'vector.dermacentor_variabilis',  predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.borrelia',              target: 'vector.ixodes_pacificus',        predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.anaplasma',             target: 'vector.ixodes_pacificus',        predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.babesia',               target: 'vector.ixodes_pacificus',        predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.y_pestis',              target: 'vector.oropsylla_montana',       predicate: 'transmittedBy' }},
    { data: { source: 'pathogen.y_pestis',              target: 'vector.xenopsylla_cheopis',      predicate: 'transmittedBy' }},

    // ---- reservoirIn: pathogen -> reservoir host ----
    { data: { source: 'pathogen.wnv',          target: 'reservoir.passerine_birds', predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.slev',         target: 'reservoir.passerine_birds', predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.sin_nombre',   target: 'reservoir.deer_mouse',       predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.y_pestis',     target: 'reservoir.gunnison_prairie_dog', predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.y_pestis',     target: 'reservoir.rock_squirrel',    predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.f_tularensis', target: 'reservoir.cottontail',       predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.f_tularensis', target: 'reservoir.jackrabbit',       predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.rickettsia_rickettsii', target: 'reservoir.dogs',    predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.rabies',       target: 'reservoir.bats',             predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.rabies',       target: 'reservoir.skunks',           predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.rabies',       target: 'reservoir.foxes',            predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.h5n1',         target: 'reservoir.waterfowl',        predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.h5n1',         target: 'reservoir.dairy_cattle',     predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.cwd_prion',    target: 'reservoir.deer_elk',         predicate: 'reservoirIn' }},
    { data: { source: 'pathogen.coccidioides', target: 'reservoir.desert_soil',      predicate: 'reservoirIn' }},

    // ---- targetsFocusArea (pathogen -> the WV focus-area / disease group) ----
    { data: { source: 'pathogen.wnv',                  target: 'focus.wnv',         predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.slev',                 target: 'focus.vector_borne', predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.dengue',               target: 'focus.vector_borne', predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.zika',                 target: 'focus.vector_borne', predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.sin_nombre',           target: 'focus.hantavirus',  predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.y_pestis',             target: 'focus.plague',      predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.f_tularensis',         target: 'focus.tularemia',   predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.rickettsia_rickettsii', target: 'focus.rmsf',       predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.rabies',               target: 'focus.rabies',      predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.h5n1',                 target: 'focus.hpai',        predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.cwd_prion',            target: 'focus.cwd',         predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.borrelia',             target: 'focus.vector_borne', predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.anaplasma',            target: 'focus.vector_borne', predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.babesia',              target: 'focus.vector_borne', predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.leptospira',           target: 'focus.zoonotic',    predicate: 'targetsFocusArea' }},
    { data: { source: 'pathogen.coccidioides',         target: 'focus.zoonotic',    predicate: 'targetsFocusArea' }},

    // ---- surveilledBy: pathogen -> resource ----
    { data: { source: 'pathogen.wnv',                  target: 'resource.adhs',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.wnv',                  target: 'resource.mcdph_mcesd',        predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.wnv',                  target: 'resource.pcdh',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.slev',                 target: 'resource.adhs',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.slev',                 target: 'resource.mcdph_mcesd',        predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.sin_nombre',           target: 'resource.adhs',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.sin_nombre',           target: 'resource.navajo_ec',          predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.sin_nombre',           target: 'resource.coconino_hhs',       predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.sin_nombre',           target: 'resource.neon',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.y_pestis',             target: 'resource.adhs',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.y_pestis',             target: 'resource.usda_aphis_ws',      predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.y_pestis',             target: 'resource.nau_pmi',            predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.y_pestis',             target: 'resource.coconino_hhs',       predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.f_tularensis',         target: 'resource.adhs',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.rickettsia_rickettsii', target: 'resource.adhs',              predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.rickettsia_rickettsii', target: 'resource.ua_extension_tickcheck', predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.rabies',               target: 'resource.adhs',               predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.rabies',               target: 'resource.usda_aphis_ws',      predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.h5n1',                 target: 'resource.azgfd',              predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.h5n1',                 target: 'resource.usfws_az',           predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.h5n1',                 target: 'resource.azvdl',              predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.h5n1',                 target: 'resource.usgs_nwhc',          predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.cwd_prion',            target: 'resource.azgfd',              predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.borrelia',             target: 'resource.ua_extension_tickcheck', predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.anaplasma',            target: 'resource.ua_extension_tickcheck', predicate: 'surveilledBy' }},
    { data: { source: 'pathogen.babesia',              target: 'resource.ua_extension_tickcheck', predicate: 'surveilledBy' }}
  ]
};
